### ISSUE TITLE
Show `$select` warning only for endpoints that support `$select`

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/m365-developer-proxy#107]
> Feedback from Tom Morgan
> https://www.linkedin.com/feed/update/urn:li:activity:7018153776209371136/

Currently if a `GET` request passes through Microsoft Graph Developer Proxy that does not use the `$select` query string parameter we raise a warning in the proxy output.

This could lead to false positives as not all endpoints support `$select`.

**Comment by waldekmastykarz** [comment]
Good point! Initially, we implemented `$select` guidance in a very simplistic way. Let's look for ways to make it more accurate and possibly avoid false positives altogether.

**Comment by jackpoz** [comment]
Using version 0.10.0 still shows the warning:
![image](https://github.com/microsoft/m365-developer-proxy/assets/1153754/363b4161-4b1e-4967-967d-55c18dc55e03)

Chances are that https://github.com/microsoft/m365-developer-proxy/commit/dae7ec010818f084558cae4e6501cc47aa46eaf8 reintroduced the issue.

Note that the /users/{userid}/photo endpoint supports both "/$value" and "$select" , as one can for example get just the width of the image with /users/{userid}/photo?$select=width (even if Graph will return all fields anyway)

The Open API definition contains both endpoints:
'/users/{user-id}/photo':
![image](https://github.com/microsoft/m365-developer-proxy/assets/1153754/f59a2d9c-89ac-450a-b120-a9d062b462fd)

'/users/{user-id}/photo/$value':
![image](https://github.com/microsoft/m365-developer-proxy/assets/1153754/80a47778-d91d-4e91-a710-6d215fc38db2)

**Comment by waldekmastykarz** [comment]
Thank you for reporting this issue @jackpoz and sorry for the trouble. I created #303 to track this issue.
